base_url_https = 'https://jsonplaceholder.typicode.com/'
base_url_http = 'http://jsonplaceholder.typicode.com/'
post_id_url = 'comments?postId='
posts_url = 'posts'
post_id_value = '13'
new_post_id = '?id=101'
